### ISSUE TITLE
Latest opx-base-model not compiling 

### ISSUE THREAD

**Issue by paolss** [open-switch/opx-base-model#19]
configure: WARNING: unrecognized options: --disable-maintainer-mode
   dh_auto_build -O--parallel
make[1]: Entering directory '/tmp/buildd/opx-base-model-3.55.0'
YANG_PATH=/tmp/buildd/opx-base-model-3.55.0/common/yumaworks:/tmp/buildd/opx-base-model-3.55.0/rfc:/tmp/buildd/opx-base-model-3.55.0/common/dell:/tmp/buildd/opx-base-model-3.55.0/yang-models /usr/lib/opx/ar_parse_yang.sh /tmp/buildd/opx-base-model-3.55.0/common/yumaworks/yumaworks-extensions.yang ./opx ./opx
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 34, in <module>
    yf = yin_model.CPSYangModel(d)
  File "/usr/lib/opx/py/yin_model.py", line 153, in __init__
    self.model = ctx['file-finder'].load(self.filename)
  File "/usr/lib/opx/py/yin_model.py", line 91, in load
    return self.get_parsed_yin(yang_file, prefix)
  File "/usr/lib/opx/py/yin_model.py", line 53, in get_parsed_yin
    f = self.get_yin_file(filename)
  File "/usr/lib/opx/py/yin_model.py", line 41, in get_yin_file
    yin_utils.create_yin_file(filename, yin_file)
  File "/usr/lib/opx/py/yin_utils.py", line 47, in create_yin_file
    run_cmd(['pyang', '-o', yin_file, '-f', 'yin', yang_file])
  File "/usr/lib/opx/py/yin_utils.py", line 24, in run_cmd
    p = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
rm: cannot remove './opx/yumaworks-extensions.h': No such file or directory
Makefile:1615: recipe for target 'opx/yumaworks-extensions-stamp' failed
make[1]: *** [opx/yumaworks-extensions-stamp] Error 1
make[1]: Leaving directory '/tmp/buildd/opx-base-model-3.55.0'
dh_auto_build: make -j1 returned exit code 2
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
W: no hooks of type C found -- ignoring
I: unmounting /var/cache/pbuilder/result filesystem
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
 -> Cleaning COW directory
  forking: rm -rf /var/cache/pbuilder/build//cow.4549
gbp:error: 'git-pbuilder' failed: it exited with 1

**Comment by JunhoSuh** [comment]
Hi,

Do you find the solution for this?
I think it seems pyang is not installed in the build host.

**Comment by jeff-yin** [comment]
We haven't been seeing this issue in the latest OPX. @JunhoSuh 's solution makes sense; make sure you do a pip install pyang.

Closing this issue for now. Please open a new issue if you're still seeing it in the latest version of opx-base-model.
