### ISSUE TITLE
RPC definitions are incomplete

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-base-model#22]
Most RPC definitions do not fully describe all of their arguments. For example, the following rpc in dell-base-if.yang has only one argument described - operation. The actual invocation requires specifying multiple additional arguments.

rpc set-interface {
        description "This method is used to create, delete or set multiple types of interface. For
                create operation, mac address will be allocated if it is not given within input argument.
                Currently there is only one input argument which specified operation type, user should
                use attributes of the model of corresponding interface type as extra input";
        input {
            leaf operation {
                description "Specify opertion type to configure interface";
                type operation-type;
            }
        }
    }

**Comment by rakeshdatta** [comment]
Hi Anton,

Thanks for pointing this out. Happy to help! 

To start with, can we understand the impact of this? 
You mentioned in the OPS mailer that, if you add those additional arguments (which are not present in the OPS RPC input) to the POST data of  ODL restconf, ODL will have internal YANG validation error.
Can u plz elaborate bit more? Is it just about the standards validation if failing or any functionality is affected?

Thanks

**Comment by kot-begemot-uk** [comment]
You cannot specify an argument in a yang modeled system which is not in 
the model.

So for example in ODL the only argument I am allowed to enter in 
restconf or netconf for set-interface is operation. So effectively there 
is no way to make this RPC functional.

So, for example, if I need to add an interface name argument to the rpc, 
it needs to be described in the model.

A.

**Comment by jeff-yin** [comment]
The description for this RPC has been added to the YANG model to reflect the required arguments, and this change will be reflected in the next major OPX release. An exercise is ongoing to update/clarify descriptions for other RPCs defined in opx-base-model.
