### ISSUE TITLE
Overquoting in dell-base-acl.yang

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-base-model#24]
The acl model contains quoted integer values like:

typedef packet-color {
        type enumeration {
            enum GREEN {
                value "1";
                description "Green";
            }
            enum YELLOW {
                value "2";
                description "Yellow";
            }
            enum RED {
                value "3";
                description "Red";
            }
        }
    }

**Comment by rakeshdatta** [comment]
Thanks for reaching out.
We will fix this and it will be a part of the next release.

Thanks

**Comment by rakeshdatta** [comment]
Hi Anton,

We are still working on this. We found other yang models where we need to make relevant changes. Would keep you updated.

Thanks

**Comment by jeff-yin** [comment]
@rakeshdatta has fixed this internally and the fixed model will be pushed out in the 3.0.0 release
