### ISSUE TITLE
model name does not match file name

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-base-model#25]
Multiple models have module names different from their file names. 

This is cosmetic - most yang driven systems will read all files in a directory to parse the models.

**Comment by rakeshdatta** [comment]
Hi Anton,

As you rightly pointed out, this is a cosmetic issue and does not really affect any thing. As per the IETF standard this is 'recommended' but not a 'MUST'. I don't see any urgent need to modify this.
Plz correct me. 

Thanks,
Rakesh

**Comment by rakeshdatta** [comment]
Hi Anton, 
I am closing this issue if u're ok with it. 

Thanks.

**Comment by jeff-yin** [comment]
Closing issue as per @rakeshdatta
