### ISSUE TITLE
Latest opx-base-model is still not compiling

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-base-model#32]
make[1]: Entering directory '/build/opx-base-model-3.146.0'
YANG_PATH=/build/opx-base-model-3.146.0/common/yumaworks:/build/opx-base-model-3.146.0/rfc:/build/opx-base-model-3.146.0/common/dell:/build/opx-base-model-3.146.0/yang-models /usr/lib/opx/ar_parse_yang.sh yumaworks-extensions.yang ./opx ./opx
/build/opx-base-model-3.146.0/common/yumaworks/yumaworks-extensions.yang:113: warning: the escape sequence "\
" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning
Opening /build/opx-base-model-3.146.0/common/yumaworks/yumaworks-extensions.yang yang file and placing it in /tmp/tmp9FKrhS/yumaworks-extensions.yin
yumaworks-extensions
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 36, in <module>
    with yin_model.CPSYangModel(d) as yf:    
  File "/usr/lib/opx/py/yin_model.py", line 127, in __init__
    self.model = self.context['loader'].load(self.filename)
  File "/usr/lib/opx/py/yin_model.py", line 94, in load
    return self.get_parsed_yin(yang_file, prefix)
  File "/usr/lib/opx/py/yin_model.py", line 78, in get_parsed_yin
    _model.load(prefix=prefix)
  File "/usr/lib/opx/py/yin_cps.py", line 124, in load
    self.context.get_yang_nodes(self.filename))
  File "/usr/lib/opx/py/cps_context.py", line 141, in get_yang_nodes
    _oas_file = self.__details['openapi-spec'].get_openapi_file(yang_file)
  File "/usr/lib/opx/py/yin_utils.py", line 85, in get_openapi_file
    self.mkdirOas(),
  File "/usr/lib/opx/py/yin_utils.py", line 62, in mkdirOas
    p = subprocess.Popen(['ar_tool.py','sysroot'],stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
rm: cannot remove './opx/yumaworks-extensions.h': No such file or directory
Makefile:2098: recipe for target 'opx/yumaworks-extensions-stamp' failed
make[1]: *** [opx/yumaworks-extensions-stamp] Error 1
make[1]: Leaving directory '/build/opx-base-model-3.146.0'
dh_auto_build: make -j1 returned exit code 2
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
I: copying local configuration
E: Failed autobuilding of package
I: user script /var/cache/pbuilder/build/cow.17028/tmp/hooks/C05shell starting
I: user script /var/cache/pbuilder/build/cow.17028/tmp/hooks/C05shell finished
I: unmounting /mnt/pool/stretch-amd64 filesystem
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: Cleaning COW directory
I: forking: rm -rf /var/cache/pbuilder/build/cow.17028
gbp:error: 'git-pbuilder' failed: it exited with 1

I already installed pyang, as suggested in issue#19, but the result is still the same.

Any more suggestion is appreciated.

**Comment by GarrickHe** [comment]
@jimmymagemtek , 

What command did you use to start the build?

Thanks,
Garrick

**Comment by jeff-yin** [comment]
Should be fixed by https://github.com/open-switch/opx-base-model/pull/33

**Comment by jeff-yin** [comment]
Closing the issue for now as the fix has been merged. Let us know (reopen this or file a new one) if you still see the problem.
