### ISSUE TITLE
opx-base-model is not compiling~

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-base-model#35]
This issue is just like issue #19, and I already repo the lasted version while got the same result. And I am sure I got pyang installed:

dpkg-source -i(?:^|/)\.git(attributes)?(?:$|/.*$) -I.git -b opx-base-model-3.151.0
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format '1.0'
dpkg-source: info: building opx-base-model in opx-base-model_3.151.0.tar.gz
dpkg-source: info: building opx-base-model in opx-base-model_3.151.0.dsc
 debian/rules build
dh build  --with autoreconf --parallel
   dh_testdir
   dh_update_autotools_config
   dh_autoreconf
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
configure.ac:8: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
Makefile.am: installing './depcomp'
   dh_auto_configure
	./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for gawk... (cached) mawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... (cached) ranlib
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for memmove... yes
checking for memset... yes
checking for strstr... yes
checking for strtoul... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing mkdir commands
   dh_auto_build
	make -j1
make[1]: Entering directory '/build/opx-base-model-3.151.0'
YANG_PATH=/build/opx-base-model-3.151.0/common/yumaworks:/build/opx-base-model-3.151.0/rfc:/build/opx-base-model-3.151.0/common/dell:/build/opx-base-model-3.151.0/yang-models /usr/lib/opx/ar_parse_yang.sh yumaworks-extensions.yang ./opx ./opx
Opening /build/opx-base-model-3.151.0/common/yumaworks/yumaworks-extensions.yang yang file and placing it in /tmp/tmpJUX_26/yumaworks-extensions.yin
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 36, in <module>
    with yin_model.CPSYangModel(d) as yf:    
  File "/usr/lib/opx/py/yin_model.py", line 127, in __init__
    self.model = self.context['loader'].load(self.filename)
  File "/usr/lib/opx/py/yin_model.py", line 94, in load
    return self.get_parsed_yin(yang_file, prefix)
  File "/usr/lib/opx/py/yin_model.py", line 78, in get_parsed_yin
    _model.load(prefix=prefix)
  File "/usr/lib/opx/py/yin_cps.py", line 124, in load
    self.context.get_yang_nodes(self.filename))
  File "/usr/lib/opx/py/cps_context.py", line 139, in get_yang_nodes
    _yin_file = self.__details['yin-loader'].get_yin_file(yang_file)
  File "/usr/lib/opx/py/yin_utils.py", line 45, in get_yin_file
    create_yin_file(filename, yin_file)
  File "/usr/lib/opx/py/yin_utils.py", line 119, in create_yin_file
    general_utils.run_cmd(['pyang', '-o', yin_file, '-f', 'yin', yang_file])
  File "/usr/lib/opx/py/general_utils.py", line 5, in run_cmd
    p = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
rm: cannot remove './opx/yumaworks-extensions.h': No such file or directory
Makefile:2098: recipe for target 'opx/yumaworks-extensions-stamp' failed
make[1]: *** [opx/yumaworks-extensions-stamp] Error 1
make[1]: Leaving directory '/build/opx-base-model-3.151.0'
dh_auto_build: make -j1 returned exit code 2
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
I: copying local configuration
E: Failed autobuilding of package
I: user script /var/cache/pbuilder/build/cow.6350/tmp/hooks/C05shell starting
I: user script /var/cache/pbuilder/build/cow.6350/tmp/hooks/C05shell finished
I: unmounting /mnt/pool/stretch-amd64 filesystem
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: Cleaning COW directory
I: forking: rm -rf /var/cache/pbuilder/build/cow.6350
gbp:error: 'git-pbuilder' failed: it exited with 1

**Comment by rakeshdatta** [comment]
**Hi @jimmymagemtek  
Can you plz try below and check if it builds.**

For Latest:
```
-	git clone https://github.com/open-switch/opx-base-model.git
-	git clone https://github.com/open-switch/opx-build.git
-	opx-build/scripts/opx_run opx_build opx-base-model
```

Fir 2.3.1:
```
-	git clone https://github.com/open-switch/opx-base-model.git
-	git clone https://github.com/open-switch/opx-build.git
-	cd opx-base-model
-	git checkout v2.3.1
-	cd ..
-	DIST=jessie OPX_RELEASE=2.3.1 opx-build/scripts/opx_run opx_build opx-base-model
```


**Also, what are the steps you used to build it?**

**Comment by rakeshdatta** [comment]
@jimmymagemtek  Plz let us know how it went.

**Comment by rakeshdatta** [comment]
Hi @jimmymagemtek,
We feel that you're not seeing issue anymore. Hence, we would close this issue.
Please let us know if you have any questions.
